### ISSUE TITLE
Method user_info does not return any value

### ISSUE THREAD

**Issue by rogeliozarate** [dannyvassallo/insta_scrape#28]
If I call: 
InstaScrape.user_info("foofighters")
I get:
Capybara::ElementNotFound: Unable to find css "h2"
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:44:in `block in find'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:85:in `synchronize'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:33:in `find'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/insta_scrape-1.1.4/lib/insta_scrape.rb:123:in `block in scrape_user_info'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:291:in `within'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/insta_scrape-1.1.4/lib/insta_scrape.rb:116:in `scrape_user_info'
	from /Users/x/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/insta_scrape-1.1.4/lib/insta_scrape.rb:35:in `user_info'
	from (irb):6
	from /Users/x/.asdf/installs/ruby/2.3.3/bin/irb:11:in `<main>'

Running in OS X 10.11.6, Ruby 2.3.3
Was running OK until a couple weeks ago.

**Comment by Venca24** [comment]
Hi @rogeliozarate, I've already proposed fix of this problem to the maintainer of this gem. In the meanwhile you can directly use fixed version from my repo (https://github.com/Venca24/insta_scrape).
